In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

## Data Preparation

In [2]:
#Let's do the value counts of other columns (STATUS)
application_status_counts = application_df['STATUS'].value_counts()
application_status_counts

1    34294
0        5
Name: STATUS, dtype: int64

In [3]:
#Since we saw that the number of status = 0 is really low, we drop it
application_df.drop(columns=["STATUS"])

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1M-5M,N,36500179,0

In [4]:
#Let's do the value counts of other columns (SPECIAL_CONSIDERATIONS)
application_status_counts = application_df['SPECIAL_CONSIDERATIONS'].value_counts()
application_status_counts

N    34272
Y       27
Name: SPECIAL_CONSIDERATIONS, dtype: int64

In [5]:
#Since we saw that the number of SPECIAL_CONSIDERATIONS is really low, we drop it
application_df = application_df.drop(columns=["SPECIAL_CONSIDERATIONS"])
application_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,36500179,0

In [6]:
#DROP EIN because it is isn't helpful
application_df = application_df.drop(columns=["EIN"])
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,36500179,0

In [9]:
#Let's investigate if there is replicate "NAMES"
application_name_counts = application_df['NAME'].value_counts()
application_name_counts

Other                                                                    19803
PARENT BOOSTER USA INC                                                    1260
TOPS CLUB INC                                                              765
UNITED STATES BOWLING CONGRESS INC                                         700
WASHINGTON STATE UNIVERSITY                                                492
                                                                         ...
VETERANS OF FOREIGN WARS OF THE UNITED STATES DEPT OF COLORADO               5
COLLEGE AND UNIVERSITY PROFESSIONAL ASSOCIATION FOR HUMAN SERVICES           5
UNITED ASSOCIATION OF JOURNEYMEN & APPRENTICES OF THE PLUMBING & PIPE        5
INTERNATIONAL ORDER OF THE RAINBOW GIRLS THE SUPREME ASSEMBLY                5
COUNTRY DANCE & SONG SOCIETY INC                                             5
Name: NAME, Length: 403, dtype: int64

In [11]:

# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = list(application_name_counts[application_name_counts <= 5].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                    20043
PARENT BOOSTER USA INC                                    1260
TOPS CLUB INC                                              765
UNITED STATES BOWLING CONGRESS INC                         700
WASHINGTON STATE UNIVERSITY                                492
                                                         ...
FLEET RESERVE ASSOCIATION                                    6
THE INTERIOR DESIGN SOCIETY INC                              6
MONTANA CONGRESS OF PARENTS TEACHERS STUDENTS                6
OFFICE AND PROFESSIONAL EMPLOYEES INTERNATIONAL UNION        6
BETA BETA BETA BIOLOGICAL SOCIETY                            6
Name: NAME, Length: 355, dtype: int64

In [12]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [13]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(application_type_counts[application_type_counts < 500].index)
    
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [14]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
application_classification_counts = application_df["CLASSIFICATION"].value_counts()
application_classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2561        1
C2380        1
C5200        1
C2600        1
C2570        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [15]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
application_classification_counts = application_df["CLASSIFICATION"].value_counts()
application_classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2561        1
C2380        1
C5200        1
C2600        1
C2570        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [16]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(application_classification_counts[application_classification_counts < 1000].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [17]:
77
#  YOUR CODE GOES HERE
df = pd.get_dummies(application_df)
print(df.shape)
df.head()

(34299, 397)

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,142590,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [18]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = df["IS_SUCCESSFUL"].values
X = df.drop(columns=["IS_SUCCESSFUL"]).values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X,y)
print(y)

[1 1 0 ... 0 1 0]

In [19]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Neural Network

In [20]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
layer1Nodes = 100
layer2Nodes = 50
layer3Nodes = 10
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=layer1Nodes, input_dim=number_input_features, activation='relu'))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=layer2Nodes, input_dim=layer1Nodes, activation='relu'))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units=layer3Nodes,input_dim=layer2Nodes, activation='relu'))
# Output layer
nn.add(tf.keras.layers.Dense(units=1,input_dim=layer3Nodes, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 100)               39700
_________________________________________________________________
dense_1 (Dense)              (None, 50)                5050
_________________________________________________________________
dense_2 (Dense)              (None, 10)                510
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11
=================================================================
Total params: 45,271
Trainable params: 45,271
Non-trainable params: 0
_________________________________________________________________

In [21]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss='binary_crossentropy', optimizer="adam", metrics=['accuracy'])

In [22]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train, epochs = 300)

Epoch 1/300
804/804 [==============================] - 4s 3ms/step - loss: 0.4707 - accuracy: 0.7774
Epoch 2/300
804/804 [==============================] - 3s 4ms/step - loss: 0.4335 - accuracy: 0.7901
Epoch 3/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4284 - accuracy: 0.7930
Epoch 4/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4274 - accuracy: 0.7931
Epoch 5/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4258 - accuracy: 0.7935
Epoch 6/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4243 - accuracy: 0.7933
Epoch 7/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4235 - accuracy: 0.7957
Epoch 8/300
804/804 [==============================] - 3s 4ms/step - loss: 0.4224 - accuracy: 0.7971
Epoch 9/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4207 - accuracy: 0.7979
Epoch 10/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7970
Epoch 11/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4194 - accuracy: 0.7983
Epoch 12/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4186 - accuracy: 0.7991
Epoch 13/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4187 - accuracy: 0.7982
Epoch 14/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4176 - accuracy: 0.8005
Epoch 15/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4170 - accuracy: 0.8000
Epoch 16/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4169 - accuracy: 0.7987
Epoch 17/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4161 - accuracy: 0.7987
Epoch 18/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4157 - accuracy: 0.8002
Epoch 19/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4152 - accuracy: 0.8011
Epoch 20/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4150 - accuracy: 0.8006
Epoch 21/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4146 - accuracy: 0.8004
Epoch 22/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4141 - accuracy: 0.8014
Epoch 23/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4140 - accuracy: 0.8007
Epoch 24/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4131 - accuracy: 0.8007
Epoch 25/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4129 - accuracy: 0.8015
Epoch 26/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4128 - accuracy: 0.8007
Epoch 27/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8021
Epoch 28/300
804/804 [==============================] - 3s 4ms/step - loss: 0.4121 - accuracy: 0.8003
Epoch 29/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8016
Epoch 30/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4113 - accuracy: 0.8013
Epoch 31/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4114 - accuracy: 0.8015
Epoch 32/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4109 - accuracy: 0.8018
Epoch 33/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4102 - accuracy: 0.8022
Epoch 34/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4103 - accuracy: 0.8018
Epoch 35/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4104 - accuracy: 0.8027
Epoch 36/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4095 - accuracy: 0.8034
Epoch 37/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4094 - accuracy: 0.8035
Epoch 38/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4096 - accuracy: 0.8025
Epoch 39/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4092 - accuracy: 0.8038
Epoch 40/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4088 - accuracy: 0.8032
Epoch 41/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4084 - accuracy: 0.8034
Epoch 42/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4083 - accuracy: 0.8042
Epoch 43/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4086 - accuracy: 0.8038
Epoch 44/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4078 - accuracy: 0.8043
Epoch 45/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4080 - accuracy: 0.8036
Epoch 46/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4076 - accuracy: 0.8046
Epoch 47/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4072 - accuracy: 0.8034
Epoch 48/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4074 - accuracy: 0.8037
Epoch 49/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4076 - accuracy: 0.8041
Epoch 50/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4067 - accuracy: 0.8038
Epoch 51/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8043
Epoch 52/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4063 - accuracy: 0.8042
Epoch 53/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4067 - accuracy: 0.8043
Epoch 54/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4066 - accuracy: 0.8045
Epoch 55/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4060 - accuracy: 0.8048
Epoch 56/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8054
Epoch 57/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4055 - accuracy: 0.8045
Epoch 58/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4052 - accuracy: 0.8053
Epoch 59/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4057 - accuracy: 0.8049
Epoch 60/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4049 - accuracy: 0.8054
Epoch 61/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4050 - accuracy: 0.8050
Epoch 62/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4049 - accuracy: 0.8054
Epoch 63/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8050
Epoch 64/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4049 - accuracy: 0.8052
Epoch 65/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8057
Epoch 66/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4041 - accuracy: 0.8052
Epoch 67/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8054
Epoch 68/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8064
Epoch 69/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4042 - accuracy: 0.8055
Epoch 70/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4037 - accuracy: 0.8055
Epoch 71/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8058
Epoch 72/300
804/804 [==============================] - 3s 4ms/step - loss: 0.4034 - accuracy: 0.8067: 0s
Epoch 73/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8059
Epoch 74/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4026 - accuracy: 0.8064
Epoch 75/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8069
Epoch 76/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8063
Epoch 77/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4022 - accuracy: 0.8071
Epoch 78/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4030 - accuracy: 0.8055
Epoch 79/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4028 - accuracy: 0.8061
Epoch 80/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4021 - accuracy: 0.8059
Epoch 81/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4024 - accuracy: 0.8060
Epoch 82/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8062
Epoch 83/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4022 - accuracy: 0.8066
Epoch 84/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4021 - accuracy: 0.8060
Epoch 85/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4025 - accuracy: 0.8056
Epoch 86/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8064
Epoch 87/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4019 - accuracy: 0.8060
Epoch 88/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8062
Epoch 89/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8067
Epoch 90/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4018 - accuracy: 0.8059
Epoch 91/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4019 - accuracy: 0.8062
Epoch 92/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8066
Epoch 93/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4011 - accuracy: 0.8071
Epoch 94/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4014 - accuracy: 0.8067
Epoch 95/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8068
Epoch 96/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4017 - accuracy: 0.8068
Epoch 97/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8064
Epoch 98/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4015 - accuracy: 0.8070
Epoch 99/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4012 - accuracy: 0.8059
Epoch 100/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4015 - accuracy: 0.8066
Epoch 101/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4008 - accuracy: 0.8069
Epoch 102/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4013 - accuracy: 0.8070
Epoch 103/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4011 - accuracy: 0.8063
Epoch 104/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4014 - accuracy: 0.8067
Epoch 105/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8071
Epoch 106/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4004 - accuracy: 0.8072
Epoch 107/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4008 - accuracy: 0.8070
Epoch 108/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8067
Epoch 109/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4010 - accuracy: 0.8068
Epoch 110/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4012 - accuracy: 0.8059
Epoch 111/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4009 - accuracy: 0.8066
Epoch 112/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4007 - accuracy: 0.8069
Epoch 113/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4004 - accuracy: 0.8067
Epoch 114/300
804/804 [==============================] - 2s 3ms/step - loss: 0.4004 - accuracy: 0.8071
Epoch 115/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8066
Epoch 116/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4002 - accuracy: 0.8069
Epoch 117/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4002 - accuracy: 0.8068
Epoch 118/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4000 - accuracy: 0.8065
Epoch 119/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4011 - accuracy: 0.8064
Epoch 120/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4002 - accuracy: 0.8070
Epoch 121/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4003 - accuracy: 0.8073
Epoch 122/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4001 - accuracy: 0.8068
Epoch 123/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4011 - accuracy: 0.8072
Epoch 124/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4000 - accuracy: 0.8072
Epoch 125/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4004 - accuracy: 0.8068
Epoch 126/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4009 - accuracy: 0.8069
Epoch 127/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4004 - accuracy: 0.8067
Epoch 128/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4002 - accuracy: 0.8075
Epoch 129/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3999 - accuracy: 0.8073
Epoch 130/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4004 - accuracy: 0.8059
Epoch 131/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3998 - accuracy: 0.8071
Epoch 132/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3995 - accuracy: 0.8073
Epoch 133/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3999 - accuracy: 0.8073
Epoch 134/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4003 - accuracy: 0.8066
Epoch 135/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4000 - accuracy: 0.8076
Epoch 136/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3994 - accuracy: 0.8077
Epoch 137/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4001 - accuracy: 0.8084
Epoch 138/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4000 - accuracy: 0.8073
Epoch 139/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3995 - accuracy: 0.8068
Epoch 140/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4002 - accuracy: 0.8077
Epoch 141/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3995 - accuracy: 0.8080
Epoch 142/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3998 - accuracy: 0.8073
Epoch 143/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3998 - accuracy: 0.8069
Epoch 144/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4001 - accuracy: 0.8075
Epoch 145/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3992 - accuracy: 0.8076
Epoch 146/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3992 - accuracy: 0.8078
Epoch 147/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4002 - accuracy: 0.8072
Epoch 148/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3999 - accuracy: 0.8074
Epoch 149/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3992 - accuracy: 0.8070
Epoch 150/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3993 - accuracy: 0.8072
Epoch 151/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4002 - accuracy: 0.8077
Epoch 152/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3994 - accuracy: 0.8073
Epoch 153/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3994 - accuracy: 0.8075
Epoch 154/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3994 - accuracy: 0.8080
Epoch 155/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3999 - accuracy: 0.8077
Epoch 156/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3989 - accuracy: 0.8075
Epoch 157/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3990 - accuracy: 0.8076
Epoch 158/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3998 - accuracy: 0.8077
Epoch 159/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3992 - accuracy: 0.8072
Epoch 160/300

804/804 [==============================] - 1s 2ms/step - loss: 0.3992 - accuracy: 0.8068
Epoch 161/300
804/804 [==============================] - 1s 2ms/step - loss: 0.4001 - accuracy: 0.8071
Epoch 162/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3993 - accuracy: 0.8061
Epoch 163/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3989 - accuracy: 0.8076
Epoch 164/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3989 - accuracy: 0.8071
Epoch 165/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3993 - accuracy: 0.8076
Epoch 166/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3994 - accuracy: 0.8073
Epoch 167/300
804/804 [==============================] - 2s 2ms/step - loss: 0.4005 - accuracy: 0.8073
Epoch 168/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3988 - accuracy: 0.8080
Epoch 169/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3991 - accuracy: 0.8077
Epoch 170/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3992 - accuracy: 0.8067
Epoch 171/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3995 - accuracy: 0.8074
Epoch 172/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3987 - accuracy: 0.8061
Epoch 173/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3990 - accuracy: 0.8081
Epoch 174/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3991 - accuracy: 0.8080
Epoch 175/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3992 - accuracy: 0.8069
Epoch 176/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3984 - accuracy: 0.8068
Epoch 177/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3985 - accuracy: 0.8073
Epoch 178/300
804/804 [==============================] - 1s 2ms/step - loss: 0.3985 - accuracy: 0.8080
Epoch 179/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3986 - accuracy: 0.8077
Epoch 180/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3982 - accuracy: 0.8079
Epoch 181/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3990 - accuracy: 0.8077
Epoch 182/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3987 - accuracy: 0.8081
Epoch 183/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3987 - accuracy: 0.8076
Epoch 184/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3988 - accuracy: 0.8079
Epoch 185/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3982 - accuracy: 0.8082
Epoch 186/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3986 - accuracy: 0.8073
Epoch 187/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3985 - accuracy: 0.8076
Epoch 188/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3991 - accuracy: 0.8084
Epoch 189/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3983 - accuracy: 0.8072
Epoch 190/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3985 - accuracy: 0.8082
Epoch 191/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3985 - accuracy: 0.8079
Epoch 192/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3987 - accuracy: 0.8079
Epoch 193/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3988 - accuracy: 0.8082
Epoch 194/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8075
Epoch 195/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8077
Epoch 196/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8072
Epoch 197/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8078
Epoch 198/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3991 - accuracy: 0.8072
Epoch 199/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3985 - accuracy: 0.8082
Epoch 200/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3982 - accuracy: 0.8081
Epoch 201/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3983 - accuracy: 0.8082
Epoch 202/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8070
Epoch 203/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8078
Epoch 204/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3981 - accuracy: 0.8077
Epoch 205/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3981 - accuracy: 0.8080
Epoch 206/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8069
Epoch 207/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3986 - accuracy: 0.8076
Epoch 208/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3984 - accuracy: 0.8077
Epoch 209/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3984 - accuracy: 0.8077
Epoch 210/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3983 - accuracy: 0.8084
Epoch 211/300
804/804 [==============================] - 3s 4ms/step - loss: 0.3986 - accuracy: 0.8077
Epoch 212/300
804/804 [==============================] - 3s 3ms/step - loss: 0.4008 - accuracy: 0.8085
Epoch 213/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3977 - accuracy: 0.8085
Epoch 214/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3987 - accuracy: 0.8073
Epoch 215/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3983 - accuracy: 0.8082
Epoch 216/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3997 - accuracy: 0.8075
Epoch 217/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3987 - accuracy: 0.8086
Epoch 218/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8073
Epoch 219/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3978 - accuracy: 0.8079
Epoch 220/300
804/804 [==============================] - 4s 4ms/step - loss: 0.3981 - accuracy: 0.8081
Epoch 221/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8083
Epoch 222/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8081
Epoch 223/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8087
Epoch 224/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3981 - accuracy: 0.8081
Epoch 225/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8076
Epoch 226/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3984 - accuracy: 0.8078
Epoch 227/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3982 - accuracy: 0.8070
Epoch 228/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8079
Epoch 229/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3992 - accuracy: 0.8084
Epoch 230/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3979 - accuracy: 0.8085
Epoch 231/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8082
Epoch 232/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8084
Epoch 233/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3982 - accuracy: 0.8083
Epoch 234/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3981 - accuracy: 0.8077
Epoch 235/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3983 - accuracy: 0.8079
Epoch 236/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3980 - accuracy: 0.8080
Epoch 237/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8084
Epoch 238/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3979 - accuracy: 0.8082
Epoch 239/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3978 - accuracy: 0.8077
Epoch 240/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8087
Epoch 241/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8084
Epoch 242/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8081
Epoch 243/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3996 - accuracy: 0.8077
Epoch 244/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3989 - accuracy: 0.8076
Epoch 245/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3982 - accuracy: 0.8080
Epoch 246/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3978 - accuracy: 0.8076
Epoch 247/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3978 - accuracy: 0.8070
Epoch 248/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8079
Epoch 249/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8090
Epoch 250/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8081
Epoch 251/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8078
Epoch 252/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8084
Epoch 253/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8082
Epoch 254/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8077
Epoch 255/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8088
Epoch 256/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8082
Epoch 257/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3986 - accuracy: 0.8077
Epoch 258/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3978 - accuracy: 0.8086
Epoch 259/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8080
Epoch 260/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8080
Epoch 261/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8083
Epoch 262/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8076
Epoch 263/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8084
Epoch 264/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8082
Epoch 265/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8081
Epoch 266/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3977 - accuracy: 0.8090
Epoch 267/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8083
Epoch 268/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3980 - accuracy: 0.8081
Epoch 269/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8082
Epoch 270/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3991 - accuracy: 0.8076
Epoch 271/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3977 - accuracy: 0.8085
Epoch 272/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8082
Epoch 273/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3969 - accuracy: 0.8083
Epoch 274/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8080
Epoch 275/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3982 - accuracy: 0.8082
Epoch 276/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8086
Epoch 277/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3978 - accuracy: 0.8084
Epoch 278/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3978 - accuracy: 0.8086
Epoch 279/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3980 - accuracy: 0.8077
Epoch 280/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3982 - accuracy: 0.8085
Epoch 281/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3971 - accuracy: 0.8090
Epoch 282/300
804/804 [==============================] - 3s 3ms/step - loss: 0.3975 - accuracy: 0.8082
Epoch 283/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8088
Epoch 284/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3973 - accuracy: 0.8082
Epoch 285/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3969 - accuracy: 0.8078
Epoch 286/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8084
Epoch 287/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3982 - accuracy: 0.8088
Epoch 288/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3986 - accuracy: 0.8090
Epoch 289/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3994 - accuracy: 0.8079
Epoch 290/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3971 - accuracy: 0.8083
Epoch 291/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8079
Epoch 292/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3978 - accuracy: 0.8088
Epoch 293/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3973 - accuracy: 0.8080
Epoch 294/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3982 - accuracy: 0.8083
Epoch 295/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8082
Epoch 296/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8087
Epoch 297/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8087
Epoch 298/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8088
Epoch 299/300
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8084
Epoch 300/300
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8082

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5190 - accuracy: 0.7924
Loss: 0.5189638733863831, Accuracy: 0.7924198508262634

In [26]:
nn.save("lphabetSoupCharity_Optimization.h5")

## Random Forest

In [28]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [29]:
random_forest_model = RandomForestClassifier(n_estimators = 150)
rf_model = random_forest_model.fit(X_train_scaled, y_train)
y_pred = random_forest_model.predict(X_test_scaled)
score = accuracy_score(y_test,y_pred) * 100
print(f"The accuracy of the random forest model is {score}" )

The accuracy of the random forest model is 77.9591836734694